### ISSUE TITLE
Continue here from WP Tavern post :)

### ISSUE THREAD

**Issue by Marcoevich** [bearded-avenger/wp-live-search#5]
Hey Nick!

Thanks for your reply on the WP tavern post. let us continue discussion here, since I still believe there may be some kind of bug with it.

I have tested the search string you provided me with in the following manner:

http://test.nl/wp-json/posts?type=bewindvoerders&filter[s]=camiel

It returns the following results:

[{"ID":171,"title":"Camiel Fennis","status":"publish","type":"bewindvoerders","author":{"ID":1,"username":"rick","name":"admin","first_name":"Rick","last_name":"Gommers","nickname":"admin","slug":"rick","URL":"","avatar":"http:\/\/0.gravatar.com\/avatar\/0babac933506ad1047996370e0170b47?s=96","description":"","registered":"2015-02-09T10:30:10+00:00","meta":{"links":{"self":"http:\/\/test.nl\/wp-json\/users\/1","archives":"http:\/\/test.nl\/wp-json\/users\/1\/posts"}}},"content":"","parent":null,"link":"http:\/\/test.nl\/bewindvoerders\/camiel-fennis\/","date":"2015-02-22T15:06:40","modified":"2015-05-12T14:48:07","format":"standard","slug":"camiel-fennis","guid":"http:\/\/test.nl\/?post_type=bewindvoerders&#038;p=171","excerpt":null,"menu_order":0,"comment_status":"closed","ping_status":"closed","sticky":false,"date_tz":"Europe\/Amsterdam","date_gmt":"2015-02-22T14:06:40","modified_tz":"Europe\/Amsterdam","modified_gmt":"2015-05-12T12:48:07","meta":{"links":{"self":"http:\/\/test.nl\/wp-json\/posts\/171","author":"http:\/\/test.nl\/wp-json\/users\/1","collection":"http:\/\/test.nl\/wp-json\/posts","replies":"http:\/\/test.nl\/wp-json\/posts\/171\/comments","version-history":"http:\/\/test.nl\/wp-json\/posts\/171\/revisions"}},"terms":[]}]

Now, from this response I can see that it returns a post from my "bewindvoerders" CPT, called "camiel fennis".

However, the plugin returns this. "camiel" is not even in the results listed:

![search results](http://i.stack.imgur.com/SD5yy.jpg)

**Comment by bearded-avenger** [comment]
good catch! i was appending them in reverse. ;)

**Comment by bearded-avenger** [comment]
I also just added multiple post type support. It works like this `[wp_live_search type="ideas,page" multi="true"]`

You can test using the dev branch download if you like: https://github.com/bearded-avenger/wp-live-search/archive/dev.zip

**Comment by Marcoevich** [comment]
Hehe nice :)

I have tried your dev fix. Works very good! It returns just one result, and exactly the result that I wanted. Great job :)

Cheers!

**Comment by bearded-avenger** [comment]
Happy to help! I'll have this version out tomorrow on the WordPress plugin repo.
