### ISSUE TITLE
PHP snippet and custom meta keys

### ISSUE THREAD

**Issue by Marcoevich** [bearded-avenger/wp-live-search#6]
Hey Nick :)

I have a few ideas/questions for your plugin:
- Do you have a php snippet so we can add the plugin to theme files like header.php? something like <?php wp_live_search ?> or <?php wp_live_search('type', 'results', 'compact') ?>
- Could you add support for searching trough custom meta keys? It would be supperb if you could support meta keys defined by Advanced Custom Fields plugin for example :)

Cheers!

Rick

**Comment by bearded-avenger** [comment]
Yep check out this template function, it's essentially a wrapper for do_shortcode. https://github.com/bearded-avenger/wp-live-search/blob/master/public/includes/template-function.php#L10

Right now the REST API doesn't allow searching through post meta keys, as those are considered private. We'd have to surface them, which would surface ALL private meta keys. For the time being we're sticking to native WordPress search.

**Comment by Marcoevich** [comment]
Allright that looks good :) Thanks nick!

**Comment by bearded-avenger** [comment]
no problem! happy to help :)
